"""003

Revision ID: 43d180772dbc
Revises: 1eb7b3ecea9b
Create Date: 2026-08-31 22:29:29.441956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d180772dbc'
down_revision: Union[str, Sequence[str], None] = '1eb7b3ecea9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_integrations', sa.Column('integration_account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'agent_integrations', 'integration_accounts', ['integration_account_id'], ['id'])
    op.add_column('agent_tool_assignments', sa.Column('tool_name', sa.String(length=100), nullable=True))
    op.add_column('agent_tool_assignments', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_tool_assignments', 'is_active')
    op.drop_column('agent_tool_assignments', 'tool_name')
    op.drop_constraint(None, 'agent_integrations', type_='foreignkey')
    op.drop_column('agent_integrations', 'integration_account_id')
    # ### end Alembic commands ###
